# Generated by Django 5.0.1 on 2024-01-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdoctors',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
