# Generated by Django 5.0.1 on 2024-01-25 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_reviewdoctors_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activate', models.BooleanField(blank=True, default=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorSaved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userSaved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Doctor',
                'verbose_name_plural': 'Saved Doctors',
                'db_table': 'table_saved_doctors',
            },
        ),
    ]
