# Generated by Django 5.0.1 on 2024-01-27 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_saveddoctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PATIENT_SENT_APPOINTMENT', 'PATIENT_SENT_APPOINTMENT'), ('PATIENT_CANCELLED_APPOINTMENT', 'PATIENT_CANCELLED_APPOINTMENT'), ('PATIENT_SENDING_BACK_APPOINTMENT', 'PATIENT_SENDING_BACK_APPOINTMENT'), ('DOCTOR_CONFIRMED_APPOINTMENT', 'DOCTOR_CONFIRMED_APPOINTMENT'), ('DOCTOR_CANCELLED_APPOINTMENT', 'DOCTOR_CANCELLED_APPOINTMENT'), ('APPOINTMENT_IS_ONGOING', 'APPOINTMENT_IS_ONGOING'), ('APPOINTMENT_IS_COMPLETED', 'APPOINTMENT_IS_COMPLETED'), ('MESSAGE_SENT', 'MESSAGE_SENT')], max_length=255)),
                ('is_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('appointments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationAppointments', to='authentification.makeappointments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationCustomUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
                'db_table': 'table_notification',
            },
        ),
    ]
