# Generated by Django 5.0.1 on 2024-02-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentification', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupCategories', to='auth.group'),
        ),
    ]
