# Generated by Django 5.0.1 on 2024-01-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_notification'),
        ('chat', '0002_conversation_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convertaionAppointments', to='authentification.makeappointments'),
        ),
    ]
