on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            cd /var/www/clinic_app
            git pull
            cd /var/www/clinic_app/back_end
            source env/bin/activate
            
            python3 -m pip install -r requirements.txt
            python3 manage.py migrate
            deactivate
            sudo systemctl start clinic.socket
            sudo systemctl enable clinic.socket
            sudo systemctl daemon-reload
            sudo systemctl restart clinic
      
            echo "Deployed at BackEnd"
